#! python3  # noqa E265

"""Generate documentation table of settings and environment variables."""

# standard
import sys
from dataclasses import asdict
from pathlib import Path

# move into project package
sys.path.insert(0, f"{Path(__file__).parent.parent.resolve()}")


# plugin
from qtribu.toolbelt.preferences import PREFIX_ENV_VARIABLE, PlgSettingsStructure

# -- variables --
output_md_file: Path = Path(__file__).parent.parent.joinpath(
    "docs/static/_autogenerated/settings_env_vars_table.md"
)

# -- main --

# header of the table
output_md_file.write_text(
    "| Paramètre | Variable d'environnement | Valeur par défaut |\n"
    "| :-------- | :----------------------: | :---------------: |\n",
    encoding="utf-8",
)

print(asdict(PlgSettingsStructure()))


out_markdown: str = ""
for k, v in asdict(PlgSettingsStructure()).items():
    env_var_name: str = f"{PREFIX_ENV_VARIABLE}{k}".upper()
    default_value: str = repr(v).replace(
        "|", "\\|"
    )  # escape pipe char for markdown table

    out_markdown += f"| {k} | `{env_var_name}` | {default_value} |\n"

with output_md_file.open("a", encoding="utf-8") as md_file:
    md_file.write(out_markdown)
