#!python3

"""
Configuration for project documentation using Sphinx.
"""

# standard
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Union

# 3rd party
import keepachangelog

# move into project package
sys.path.insert(0, f"{Path(__file__).parent.parent.resolve()}")

# Package
from qtribu import __about__

# -- Build environment -----------------------------------------------------
logger: logging.Logger = logging.getLogger(__name__)

# -- Project information -----------------------------------------------------
changes: dict[str, dict] = keepachangelog.to_dict("../CHANGELOG.md")
latest_version: str = [
    v for v in changes.keys() if v not in ("Unreleased", "version_tag")
][0]


author: str = __about__.__author__
copyright: str = __about__.__copyright__
description: str = __about__.__summary__
project: str = __about__.__title__
version = release = __about__.__version__

github_doc_root: str = f"{__about__.__uri__}/tree/master/docs/"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions: list[str] = [
    # Sphinx included
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.extlinks",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    # 3rd party
    "myst_parser",
    "sphinx_copybutton",
    "sphinxext.opengraph",
    "sphinx_rtd_theme",
    "sphinx_sitemap",
]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix: dict[str, str] = {".md": "markdown", ".rst": "restructuredtext"}
autosectionlabel_prefix_document = True
# The master toctree document.
master_doc: str = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language: str = "fr"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns: list[str] = [
    "_build",
    ".venv",
    "Thumbs.db",
    ".DS_Store",
    "_output",
    "ext_libs",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style: str = "sphinx"


# -- Options for HTML output -------------------------------------------------

# -- Theme

# final URL
html_baseurl: str = __about__.__uri_homepage__
html_favicon: str = str(__about__.__icon_path__)
html_logo: str = str(__about__.__icon_path__)
html_sidebars: dict[str, list[str]] = {
    "**": ["globaltoc.html", "relations.html", "sourcelink.html", "searchbox.html"]
}
# html_static_path = ["_static"]
html_theme: str = "sphinx_rtd_theme"
html_theme_options: dict[str, Union[bool, int, str]] = {
    "logo_only": False,
    "prev_next_buttons_location": "both",
    "style_external_links": True,
    "style_nav_header_background": "SteelBlue",
    # Toc options
    "collapse_navigation": True,
    "includehidden": False,
    "navigation_depth": 4,
    "sticky_navigation": True,
    "titles_only": False,
}

# -- EXTENSIONS --------------------------------------------------------

# Sphinx API doc
autodoc_mock_imports: list[str] = [
    "qgis.core",
    "qgis.gui",
    "qgis.PyQt",
    "qgis.PyQt.QtCore",
    "qgis.PyQt.QtGui",
    "qgis.PyQt.QtNetwork",
    "qgis.PyQt.QtWidgets",
    "qgis.utils",
]


# Configuration for intersphinx (refer to others docs).
intersphinx_mapping: dict[str, tuple[str, None]] = {
    "PyQt5": ("https://www.riverbankcomputing.com/static/Docs/PyQt5", None),
    "PyQt6": ("https://www.riverbankcomputing.com/static/Docs/PyQt6", None),
    "python": ("https://docs.python.org/3/", None),
    "qgis": ("https://qgis.org/pyqgis/master/", None),
}

# MyST Parser
myst_enable_extensions: list[str] = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
]

myst_substitutions: dict[str, str] = {
    "author": author,
    "date_update": datetime.now().strftime("%d %B %Y"),
    "description": description,
    "qgis_version_max": __about__.__plugin_md__.get("general").get(
        "qgismaximumversion"
    ),
    "qgis_version_min": __about__.__plugin_md__.get("general").get(
        "qgisminimumversion"
    ),
    "repo_url": __about__.__uri__,
    "title": project,
    "version": version,
}

myst_url_schemes: list[str] = ["http", "https", "mailto"]

# OpenGraph
ogp_image: str = "https://cdn.geotribu.fr/img/projets-geotribu/plugin_qtribu/qtribu_article_displayed.png"
ogp_site_name: str = "QTribu : reste en qontact avec la GéoTribu"
ogp_site_url: str = __about__.__uri_homepage__
ogp_custom_meta_tags: list[str] = [
    "<meta name='twitter:card' content='summary_large_image'>",
    f'<meta property="twitter:description" content="{description}" />',
    f'<meta property="twitter:image" content="{ogp_image}" />',
    '<meta property="twitter:site" content="@geotribu" />',
    f'<meta property="twitter:title" content="{project}" />',
]


# Sphinx API doc
autodoc_mock_imports: list[str] = [
    "qgis.core",
    "qgis.gui",
    "qgis.PyQt",
    "qgis.PyQt.QtCore",
    "qgis.PyQt.QtGui",
    "qgis.PyQt.QtNetwork",
    "qgis.PyQt.QtWidgets",
    "qgis.utils",
]


# -- Functions ------------------------------------------------------------------
def generate_qdt_snippet(_) -> None:
    """Generate QDT snippet for profiles.json files."""
    logger.info("=== START GENERATING QDT SNIPPET ===")

    output_path: Path = Path("./docs/static/_autogenerated/qdt_snippet.json")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    qdt_snippet: dict[str, Union[str, bool, int]] = {
        "name": "QTribu",
        "folder_name": "qtribu",
        "official_repository": True,
        "plugin_id": 2733,
        "version": f"{latest_version}",
    }

    with output_path.open("w", encoding="UTF8") as wf:
        wf.write(json.dumps(qdt_snippet, indent=4, sort_keys=True))


# -- API Doc --------------------------------------------------------
def run_apidoc(_) -> None:
    """Run Sphinx API doc generation."""
    from sphinx.ext.apidoc import main

    logger.info("=== START SPHINX API AUTODOC ===")

    cur_dir: Path = Path(__file__).parent.resolve()
    output_path = str(cur_dir.joinpath("_apidoc").resolve())
    modules = str(cur_dir.joinpath("../qtribu/").resolve())
    exclusions: list[str] = ["../.venv", "../tests", "../CHANGELOG.md"]
    main(["-e", "-f", "-M", "-o", output_path, modules] + exclusions)


# launch setup
def setup(app) -> None:
    """Sphinx setup hook."""
    app.connect("builder-inited", run_apidoc)
    app.connect("builder-inited", generate_qdt_snippet)
